//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestA3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// A3.
    /// </summary>
    //  *** Start programmer edit section *** (A3 CustomAttributes)

    //  *** End programmer edit section *** (A3 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("A3E", new string[0])]
    [View("A3L", new string[0])]
    public class A3 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (A3 CustomMembers)

        //  *** End programmer edit section *** (A3 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "A3E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View A3E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("A3E", typeof(IIS.TestA3.A3));
                }
            }
            
            /// <summary>
            /// "A3L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View A3L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("A3L", typeof(IIS.TestA3.A3));
                }
            }
        }
    }
}
